micronaut:
  http:
    client:
      max-content-length: 1073741824
  server:
    max-request-size: 1073741824
    port: 32192
    cors:
      enabled: true
    netty:
      log-level: TRACE
    multipart:
      max-file-size: 1073741824
      enabled: true
  application:
    name: zulia-service
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
endpoints:
  routes:
    enabled: true
  stop:
    enabled: true
    sensitive: true


